# Variables 탭에서 subject 식별용 헤더 후보 (앞에서부터 우선)
SHEET_SUBJID_HEADER_ALIASES = [
    "SUBJID_batch",
    "SUBJID",
    "Subject_ID",
    "Subject ID",
]

FILTERING_COLUMNS = [
    "SUBJID_batch",
    "WT_area_Trachea",
    "WT_area_RMB",
    "WT_area_TriRUL",
    "WT_area_Bronint",
    "WT_area_RB4+5",
    "WT_area_RLL6",
    "WT_area_RLL7",
    "WT_area_TriRLL",
    "WT_area_RB9+10",
    "WT_area_LMB",
    "WT_area_TriLUL",
    "WT_area_LB1+2+3",
    "WT_area_LB1+2",
    "WT_area_LB4+5",
    "WT_area_LLB6",
    "WT_area_TriLLB",
    "WT_area_LB9+10",
    "WT_area_sRUL",
    "WT_area_sRML",
    "WT_area_sRLL",
    "WT_area_sLUL",
    "WT_area_sLLL",
    "Dh_Trachea",
    "Dh_RMB",
    "Dh_TriRUL",
    "Dh_Bronint",
    "Dh_RB4+5",
    "Dh_RLL6",
    "Dh_RLL7",
    "Dh_TriRLL",
    "Dh_RB9+10",
    "Dh_LMB",
    "Dh_TriLUL",
    "Dh_LB1+2+3",
    "Dh_LB1+2",
    "Dh_LB4+5",
    "Dh_LLB6",
    "Dh_TriLLB",
    "Dh_LB9+10",
    "Dh_sRUL",
    "Dh_sRML",
    "Dh_sRLL",
    "Dh_sLUL",
    "Dh_sLLL",
]

# COLUMN_RENAME = {
#     col: col.replace("WT_area_", "WT_")
#     for col in FILTERING_COLUMNS
#     if col.startswith("WT_area_")
# }
# 위 처럼 코딩할 수 있으며, 명시적으로 나타내기 위해 하드코딩함

HEADER_COLUMNS = [
    "SUBJID_batch",
    "WT_Trachea",
    "WT_RMB",
    "WT_TriRUL",
    "WT_Bronint",
    "WT_RB4+5",
    "WT_RLL6",
    "WT_RLL7",
    "WT_TriRLL",
    "WT_RB9+10",
    "WT_LMB",
    "WT_TriLUL",
    "WT_LB1+2+3",
    "WT_LB1+2",
    "WT_LB4+5",
    "WT_LLB6",
    "WT_TriLLB",
    "WT_LB9+10",
    "WT_sRUL",
    "WT_sRML",
    "WT_sRLL",
    "WT_sLUL",
    "WT_sLLL",
    "Dh_Trachea",
    "Dh_RMB",
    "Dh_TriRUL",
    "Dh_Bronint",
    "Dh_RB4+5",
    "Dh_RLL6",
    "Dh_RLL7",
    "Dh_TriRLL",
    "Dh_RB9+10",
    "Dh_LMB",
    "Dh_TriLUL",
    "Dh_LB1+2+3",
    "Dh_LB1+2",
    "Dh_LB4+5",
    "Dh_LLB6",
    "Dh_TriLLB",
    "Dh_LB9+10",
    "Dh_sRUL",
    "Dh_sRML",
    "Dh_sRLL",
    "Dh_sLUL",
    "Dh_sLLL",
]